### ISSUE TITLE
Error: API did not return json Issue

### ISSUE THREAD

**Issue by hl5biw** [matbmeijer/JirAgileR#2]
when I try connect my jira server with JiraAgilR tool, it commes
"Error: API did not return json Issue".
I think this issues maybe comes from api miss adressed in my server.
My jira server can access rest api like this :
http://my.server.com/issue/rest/api/2/issue/ISSUENO-4867

But this tool only fixed rest api  like this : 
http://my.server.com/issue/rest/api/issue/ISSUENO-4867

so how can I configure rest api address freely.

**Comment by matbmeijer** [comment]
Hi @hl5biw , I'll see to update the package in the following days and come back to your issue.

**Comment by matbmeijer** [comment]
Hi @hl5biw, do you mind adding your R code hiding any kind of personal information? This API wrapper calls directly the jira query language search api (JQL) endpoint. In other words, it searches the way it does within JIRA. For more information visit the following link:
[JQL The most flexible way to search jira](https://www.atlassian.com/blog/jira-software/jql-the-most-flexible-way-to-search-jira-14)
An example of a possible way of searching would be the following:
```r
library(JirAgileR)
df<-JiraQuery2R(domain ="http://my.server.com", query = "issue='ISSUENO-4867'")
```
This would call the following API endpoint:
https://my.server.com/rest/api/latest/search?jql=issue%3D%27ISSUENO-4867%27&fields=status%2Cpriority%2Ccreated%2Creporter%2Csummary%2Cdescription%2Cassignee%2Cupdated%2Cissuetype%2CfixVersions&startAt=0&maxResults=50

Log into your server, and test the api call exchanging my.server.com for your real server to test if it returns a json file. As you can see, it does not address the API endpoint you mentioned. Could it be that your server only has a http scheme and no https?

I hope this helps, let me know!

**Comment by hl5biw** [comment]
Thanks for your quick replay I tried on as follows on my note book web browser
-------- as follows ----------
**key in  web browser** : http://my,server.com/issue/rest/api/2/issue/ISSUENO-4884?jql=project=ISSUENOE&fields=key,status,summary   (** not  start https)

**respond from  server** : 
{"expand":"renderedFields,names,schema,transitions,operations,editmeta,changelog","id":"1390275","self":"http://my,server.com/issue/rest/api/2/issue/1390275","key":"ISSUENOE-4884","fields":{"summary":"HW Test","status":{"self":"http://my.server.com/issue/rest/api/2/status/1","description":"The issue is open and ready for the assignee to start work on it.","iconUrl":"http:/my.server.com/issue/images/icons/statuses/open.png","name":"Open","id":"1","statusCategory":{"self":"http:/my.server.com/issue/rest/api/2/statuscategory/2","id":2,"key":"new","colorName":"blue-gray","name":"To Do"}}}}

Thanks

**Comment by matbmeijer** [comment]
Hi @hl5biw, I made some changes so the package accepts both `https` and `http` endpoints. Please test the following code. Make sure you do not need any kind of authentication - if you do so use the `username` and `password` parameters of the `JiraQuery2R()`function:
```r
if (!require("devtools")) install.packages("devtools")
devtools::install_github("matbmeijer/JirAgileR")

df<-JiraQuery2R(domain ="http://my.server.com", query = "issue='ISSUENO-4867'")
```

Let me know if this worked!

**Comment by hl5biw** [comment]
I tried to change your source code like this
and then it works great so if it is possible to accept please modify it to afford this url of jira server configuration.
![image](https://user-images.githubusercontent.com/31296655/78612170-a915c500-78a3-11ea-9d9b-8553594e2ac8.png)

**Comment by matbmeijer** [comment]
Hi @hl5biw, the API endpoint should not be the problem - it might be the API version (which here is understood as "robust", but as the latest API is version v2, this should not be a problem either.
Do you mind sharing your code with me following the reprex standard?
[https://github.com/tidyverse/reprex](https://github.com/tidyverse/reprex)

Thank you!

**Comment by matbmeijer** [comment]
Hi @hl5biw, were you able to check on this? If I don't hear anything back in the following week I will have to close the issue. Kind regards!

**Comment by matbmeijer** [comment]
Due to inactivity issue closed
